version: '3'
services:
#  app:
#    container_name: insurance-quote
#    build: .
#    ports:
#      - "8080:8080"
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
